# Generated by Django 3.0.6 on 2020-06-11 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200611_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString0',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString3',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('[0-9][ ]*[0-9][ ]*[0-9][ ]*[0-9][ ]*[A-Za-z][ ]*[A-Za-z]')]),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='dataString5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Discarded'), (0, 'Current'), (1, 'Readonly')], null=True),
        ),
    ]
